### PR TITLE
ability to specify redirectURL

### PR DESCRIPTION
**Pull request by gaud2029**
was previously merged but removed in the whmcs 7 release.

### CODE REVIEW

**Comment by gaud2029** [comment]
travis check failed on php 5.3
WHMCS 7.x supports PHP 5.6 and 7.0

**Comment by Jeremyreiff25** [comment]
Somebody please explain to me how I get everything going for bitpay because I am lost

**Comment by pieterpoorthuis** [comment]
@Jeremyreiff25 can you explain what works for you and what does not work? What version of WHMCS are you running? If you can provide logs & screenshots, please do so via support@bitpay.com

**Comment by gaud2029** [comment]
@pieterpoorthuis can you explain why this pull request won't get merged ?

**Comment by pieterpoorthuis** [comment]
@gaud2029 Are you using BitPay's redirectURL settings (in the merchant dashboard) or do you set your customer redirectURL in WHMCS? If so, are you using a special plugin/code to set the redirectURL in WHMCS?

**Pull request merged**
